In [1]:
from mytorch.tensor import Tensor
import mytorch.nn.module as nn
from mytorch import tensor
import mytorch.nn.functional as F
import numpy as np


ModuleNotFoundError: No module named 'numpy'

# Trash

In [2]:
Tensor(1)

1

In [2]:

a = Tensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
for i in range(2):
  for j in range(3):
    out = a[i,j] * a[i,j]
    out.backward()
print(a.grad)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [16]:
A = Tensor(2.0, requires_grad = True)
B = Tensor(4.0, requires_grad = True)
# B.backward()
X = A * B
X.shape
# X.bkwrd()
# print(A.grad.data)

()

In [33]:
x = Tensor.ones(8,requires_grad=True)  # input tensor
y = Tensor.zeros(10,requires_grad=True)  # expected output
W = Tensor.randn(8, 10,requires_grad=True) # weights
b = Tensor.randn(10,requires_grad=True) # bias vector
print(f'x,y,W,b type = {[type(i) for i in [x,y,W,b]]} x,y,W,b shape = {[i.shape for i in [x,y,W,b]]}')
# w = F.Transpose().apply(W)
# w = W.T
# W.T
m =  W.T @ x
# z = m + b # output

# z = z.reshape((1, z.shape[0]))
# z.shape
# loss = F.cross_entropy(z, y)

x,y,W,b type = [<class 'mytorch.tensor.Tensor'>, <class 'mytorch.tensor.Tensor'>, <class 'mytorch.tensor.Tensor'>, <class 'mytorch.tensor.Tensor'>] x,y,W,b shape = [(8,), (10,), (8, 10), (10,)]


TypeError: unsupported operand type(s) for @: 'method' and 'Tensor'

In [28]:
loss.backward()
loss

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 10)

In [26]:
inputs = Tensor.randn(2, 4,requires_grad=True)
targets = Tensor.randn(2, 4)
mseloss = nn.MSELoss()

outputs = mseloss(inputs, targets)
outputs.backward()

print('input: ', inputs)
print('target: ', targets)
print('output: ', outputs)

outputs.shape (1,)
input:  [[ 1.15627043  3.30780495 -1.03078369 -0.85780121]
 [-0.04546688  0.79599968 -0.53521691  0.1765711 ]]
target:  [[-1.74992722  0.80385344 -0.51530238 -1.46034409]
 [-1.13188434  2.08168077  0.43265716  0.0456317 ]]
output:  2.3914676182766104, grad_fn=BackwardFunction


In [14]:
print(f'inputs.grad {inputs.grad} \noutputs.grad {outputs.grad}')

inputs.grad [[-0.07462739  0.54792054 -0.22530615  0.22018538]
 [-0.70467024  0.0639893   0.68005086  0.20458043]] 
outputs.grad None


In [5]:
outputs.plot_backward()

TypeError: len() of unsized object